### ISSUE TITLE
No existen las metodologías ágiles

### ISSUE THREAD

**Issue by JJ** [moshidev/TFG-MaquiTracker#12]
Existe el desarrollo ágil o la mentalidad ágil: https://agile-mercurial.com/2019/08/28/there-is-no-agile-methodology-or-agile-framework/

https://github.com/moshidev/TFG-MaquiTracker/blob/eb9c61df0c318222eed7e3a5189a22bef2478321/memoria/secciones/02_problema_a_resolver.tex#L8

También lo mismo que se ha dicho anteriormente: la búsqueda de citas debe ser parte del proceso integral de elaboración de la memoria.

**Comment by moshidev** [comment]
Este pie de página refiere al sentido original que se le da en el manifiesto ágil.
