### ISSUE TITLE
El problema a resolver es posiblemente mejor incluirlo en la introducción

### ISSUE THREAD

**Issue by JJ** [moshidev/TFG-MaquiTracker#13]
https://github.com/moshidev/TFG-MaquiTracker/blob/eb9c61df0c318222eed7e3a5189a22bef2478321/memoria/secciones/02_problema_a_resolver.tex#L1

Si no, no tiene sentido que se plantee una solución antes de hablar siquiera del problema. Con el problema a resolver se incluyen también los posibles clientes, a partir de lo cual se deben tomar una serie de decisiones.

**Comment by moshidev** [comment]
Me preocupa que sea demasiado largo como para una introducción. O lo dices por exponer el problema a resolver de una forma concisa en la introducción y explicar cómo definir los problemas y elegir el problema a resolver en el segundo capítulo?

**Comment by moshidev** [comment]
Me di cuenta que el problema es más conciso de lo que pensaba. El problema a resolver está en la introducción.
